### ISSUE TITLE
Users can access notes without entering passcode

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/simplenote-ios#87]
With the latest update, it is possible to open Simplenote and access notes without entering a passcode or using Touch ID even when these options are enabled.

Steps to reproduce:
1. Setup a passcode and Touch ID on the app.
2. Leave the app on the main notes list and close the app.
3. Reopen the app and notice you're prompted for the passcode or Touch ID.
4. Once you're back in the app, open a specific note. Then, press the home button to return to the homescreen.
5. Click on Simplenote again to open it. You will not be prompted for a passcode or Touch ID.

Here's a video of the issue: https://cloudup.com/cB6kVLzpyVw

This was reported in 2816916-t and confirmed through testing.

**Comment by iamgabrielma** [comment]
Reported also in 2817460-t and replicated too.

**Comment by catkit** [comment]
Also reported at another ticket 2817606-t.

**Comment by roundhill** [comment]
The app gives you a few seconds to return to the app, so it isn't annoying if you are copying and pasting something. Maybe users think this is a security concern though?

**Comment by jeremeylduvall** [comment]
@roundhill yep—I think users are viewing it as a security concern. I do like that it gives you a few seconds to return to the app for copying/pasting. However, perhaps we could shorten that time though? I just gave this a test, and I could still return to the note 10 minutes later without using Touch ID/pin code. What's the length of time we're setting here? Feels like 60 seconds would be plenty.

**Comment by roundhill** [comment]
> Feels like 60 seconds would be plenty.

Hmm, I thought it was 10 seconds. Sounds like a bug.

**Comment by jeremeylduvall** [comment]
Yeah it's much longer than that from my testing right now

**Comment by gracie** [comment]
Reported in #2823815-t

**Comment by kevmarsden** [comment]
Also reported in #2825217-t

**Comment by jeremeylduvall** [comment]
Reported in 2826252-t as well.

**Comment by dllh** [comment]
Also in #2852131-t.

**Comment by roundhill** [comment]
@jleandroperez could you have a look at this? Maybe something iOS 10 caused this.

**Comment by jleandroperez** [comment]
(Spoken via Slack, but replying here as well!). I've been assigned 100% to the Aztec Editor for a couple weeks.

We should definitely schedule a round for iOS 10 + maybe address (all of the project's) warnings, which will probably take a while. Scheduling this issue for the next milestone.

cc'ing @astralbodies

**Comment by roundhill** [comment]
Strangely, I can't reproduce this one by following the steps. @jeremeylduvall I'm curious if maybe apple fixed this in recent iOS updates, can you give it another try?

**Comment by kevmarsden** [comment]
I can still reproduce this issue on an iPad Mini (1st gen running 9.3.5), but not on my iPhone 6 (iOS 10.0.2).

**Comment by roundhill** [comment]
Ah, was able to reproduce on an iPad as well. Thanks @kevmarsden

**Comment by roundhill** [comment]
Strangely, I don't get the issue when compiling the app myself. But if I download from the app store, the issue is there.

@jleandroperez any thoughts on that? Something with the way the app store build is created?

**Comment by debex** [comment]
I updated my iPhone 6 to 10.0.2 last night, and can still reproduce this. It only happens when you exit the app while viewing the body of a note, then return. If you are on the list of notes when you exit the app, the passcode prompt appears as it should.

In case it's helpful -- I often see just a flash of the number pad for the passcode, when I am exiting the app in a note view: https://cloudup.com/cOmqeOmTeTm

**Comment by jleandroperez** [comment]
Apologies about the late reply @roundhill!. As far as i remember, there were no conditionals for touchID, based on the build kind.

It's possible the App Lifecycle is slightly different when the debugger is attached vs when it's not. Please, try reproducing the Debug build, but without LLVM hooked to it.

I would bet it's just a method that doesn't get called, when we're actually relying on that?

**Comment by KokkieH** [comment]
Had another report of this via [Twitter](https://twitter.com/user/status/820042305612763137).

**Comment by jerrysarcastic** [comment]
Also reported by a Simplenote iOS user in #3008019-t and I am able to reproduce the issue as well

**Comment by roundhill** [comment]
This is fixed via #125

Also this is a dupe of #120

**Comment by GertjanLind** [comment]
Still having issues with the security of Simplenote on my iPad mini.

**Comment by iamgabrielma** [comment]
Reported on 3018756-t

**Comment by iamgabrielma** [comment]
Added some more information on 3018756-t reply: 

>  I also noticed if you hit "Cancel" on the touch ID prompt screen, you will still gain access

**Comment by swoolz** [comment]
Reported on 3062447-t

When a note is left open, the user is still prompted for touch ID, but you can see the note in the background (screenshot in ticket.)

**Comment by iamgabrielma** [comment]
Reported on 728098-zen

**Comment by jleandroperez** [comment]
Closed as cannot repro. Simplenote Mark 4.12 / iOS 13.1.2.
